{% set version = "3.7" %}

package:
  name: libx86emu
  version: {{ version }}

source:
  url: https://github.com/wfeldt/libx86emu/archive/{{ version }}.tar.gz
  sha256: 03754aede79530baa0e862e1aad5527e9c1bd3371736b1ab5a2bc769e4a3d680

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    - {{ pin_subpackage('libx86emu', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make

test:
  commands:
    - test -f ${PREFIX}/lib/libx86emu.so
    - test -f ${PREFIX}/lib/libx86emu.so.{{ version }}
    - test -f ${PREFIX}/include/x86emu.h

about:
  home: https://github.com/wfeldt/libx86emu/
  summary: x86 emulation library
  description: |
    libx86emu is a small library to emulate x86 instructions. The focus here is
    not a complete emulation (go for qemu for this) but to cover enough for
    typical firmware blobs.

  # old style MIT but closest I could find
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
